//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experis.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumonSemestre
    {
        public int IdAlumono { get; set; }
        public int IdSemestre { get; set; }
        public int IdAlumnoSemestre { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Semestre Semestre { get; set; }
    }
}
