//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experis.Data.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExperisDBEntities : DbContext
    {
        public ExperisDBEntities()
            : base("name=ExperisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumonSemestre> AlumonSemestre { get; set; }
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Semestre> Semestre { get; set; }
        public virtual DbSet<SemestreMateria> SemestreMateria { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
