//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experis.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int IdNota { get; set; }
        public Nullable<double> PrimerNota { get; set; }
        public Nullable<double> SegundoNota { get; set; }
        public Nullable<double> TerceNota { get; set; }
        public Nullable<double> Promedio { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public Nullable<int> IdMateria { get; set; }
        public Nullable<int> IdProfesor { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
